name: Compilar y desplegar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.x
      - name: Obteniendo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore
